#NumPy Array Copy and View

In [8]:
import numpy as np

1. Create a NumPy array and make a copy of it. Modify the original array and print both
the original and copied arrays.

In [9]:
a=np.array([1,2,3,4,5])
b=a.copy()

a[2]=101

print(a)
print(b)

[  1   2 101   4   5]
[1 2 3 4 5]


2. Create a view of a NumPy array. Modify the view and print both the original and the
view. How do the results compare to using a copy?

In [10]:
a=np.array([1,2,3,4,5])

b=a.view()

b[2]=101

print(a)
print(b)

[  1   2 101   4   5]
[  1   2 101   4   5]


3. Explain the difference between array.copy() and array.view() in NumPy. Provide an
example to illustrate the difference.

In [11]:
a=np.array([1,2,3,4,5])
print("Original array ",a)

b=a.copy()
b[2]=101
print("Copy array after value changing is  ",b)
print("Original array after value changing ",a)
print()


c=a.view()
c[2]=1001
print("View array after value changing     ",c)
print("Original array after value changing ",a)

Original array  [1 2 3 4 5]
Copy array after value changing is   [  1   2 101   4   5]
Original array after value changing  [1 2 3 4 5]

View array after value changing      [   1    2 1001    4    5]
Original array after value changing  [   1    2 1001    4    5]


4. Create a 2D NumPy array and generate a view that represents only the first row.
Modify this view and print the changes in both the original array and the view.

In [12]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print("----------------------")

b=a.view()
print(b[0])
print("----------------------")

b[0,1]=9
print(b[0])
print("----------------------")
print(b)

[[1 2 3]
 [4 5 6]]
----------------------
[1 2 3]
----------------------
[1 9 3]
----------------------
[[1 9 3]
 [4 5 6]]


#Check Copy or View

5. Create a NumPy array and another array by slicing the first array. Check whether the
second array is a copy or a view of the first array.

In [13]:
a=np.array([1,2,3,4,5])

b=a[0:3]
print(b)
print("----------------------")
print(b.base)   # so it is not copy it is a view

[1 2 3]
----------------------
[1 2 3 4 5]


6. Use the np.may_share_memory() function to check if two arrays share the same
memory. Provide an example.

In [14]:
a=np.array([1,2,3,4,5,6])
b=np.array([1,2,3,4,5,6])
x=np.may_share_memory(a,b)
print(x)

False


In [15]:
a=np.array([1,2,3,4,5,6])
b=a.view()
x=np.may_share_memory(a,b)
print(x)

#if they share same memory it returns true

True


7. Create a NumPy array, then use the reshape() function on it. Check whether the
reshaped array is a view or a copy.

In [16]:
a=np.array([1,2,3,4,5,6])
b=a.reshape(2,3)
print(b.base)          #it is a view

[1 2 3 4 5 6]


#NumPy Array Shape

8. Create a NumPy array and print its shape. Then reshape it to another valid shape and
print the new shape.

In [17]:
a=np.array([1,2,3,4,5,6])
print("Original shape : ",a.shape)
b=a.reshape(2,3)
print("Reshaped shape :",b.shape)

Original shape :  (6,)
Reshaped shape : (2, 3)


9. Given a 1D array of length 12, reshape it into a 2D array with 3 rows. Then, reshape it
into a 3D array. Print the shapes at each step.

In [18]:
a=np.arange(12)
print(a)
print("----------------------")
b=a.reshape(3,4)
print(b)
print("----------------------")
print("Shape :",b.shape)
print("----------------------")

c=a.reshape(3,2,-1)
print(c)
print("----------------------")
print("Shape :",c.shape)
print("----------------------")

[ 0  1  2  3  4  5  6  7  8  9 10 11]
----------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
----------------------
Shape : (3, 4)
----------------------
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
----------------------
Shape : (3, 2, 2)
----------------------


10.Create a 3x4 matrix and then reshape it into a 2x6 matrix. Verify if reshaping changes
the data content.

In [19]:
a=np.arange(12).reshape(3,4)
print(a)
print("----------------------")
print("Shape :",a.shape)
print("----------------------")

b=a.reshape(2,6)
print(b)
print("----------------------")
print("Shape :",b.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
----------------------
Shape : (3, 4)
----------------------
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
----------------------
Shape : (2, 6)


#NumPy Array Reshaping

11.Reshape a 2D array into a 3D array. Then reshape it back to its original 2D shape.

In [20]:
a=np.arange(12).reshape(3,4)
print(a)
print("----------------------")
b=a.reshape(2,2,-1)
print(b)
print("----------------------")
print("Shape :",b.shape)
print("----------------------")
a=b.reshape(3,4)
print(a)
print("----------------------")
print("Shape :",a.shape)
print("----------------------")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
----------------------
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
----------------------
Shape : (2, 2, 3)
----------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
----------------------
Shape : (3, 4)
----------------------


12.Given a 4x4 matrix, reshape it into a 2D array with dimensions 2x8. Then, reshape it
back to 4x4.

In [21]:
a=np.arange(16).reshape(4,4)
print(a)
print("----------------------")
b=a.reshape(2,8)
print(b)
print("----------------------")
c=b.reshape(4,4)
print(c)
print("----------------------")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
----------------------
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
----------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
----------------------


13.Create a 3D array and flatten it into a 1D array using reshape(-1).

In [22]:
a=np.arange(18).reshape(2,3,3)
print(a)
print("----------------------")
b=a.reshape(-1)
print("Flattened array :",b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
----------------------
Flattened array : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


#NumPy Array Iteration

14.Create a 3x3 matrix and iterate over its elements row by row.

In [23]:
a=np.arange(9).reshape(3,3)
for i in a:
  print("Row :",i)

Row : [0 1 2]
Row : [3 4 5]
Row : [6 7 8]


15.Create a 2D array. Print index of each element including that element

In [24]:
a=np.arange(1,10).reshape(3,3)
for x,i in np.ndenumerate(a):
  print(x,i)


(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(2, 0) 7
(2, 1) 8
(2, 2) 9


16. Iterate over a 3D array and print each element, along with its corresponding index

In [25]:
a=np.arange(1,9).reshape(2,2,2)
for x,i in np.ndenumerate(a):
  print(x,i)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8


# Iterate Arrays Using nditer()


17.Create a 2D NumPy array and use np.nditer() to iterate over it. Print each element

In [26]:
a=np.arange(1,10).reshape(3,3)
for i in np.nditer(a):
  print(i)

1
2
3
4
5
6
7
8
9


18. Create a 3D array. Print each element and its corresponding index.

In [27]:
a=np.arange(1,9).reshape(2,2,2)
for x,i in np.ndenumerate(a):
  print(x,i)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8


19. Create a 6D array and use nditer() and print each element .

In [28]:
a=np.array([1,2,3],ndmin=6)
print("Shape  :",a.shape)
for i in np.nditer(a):
  print(i)

Shape  : (1, 1, 1, 1, 1, 3)
1
2
3


# Iterating with Different Data Types


20. Create a 2D integer array and use nditer() to iterate over it as if it were an float array.
Print the elements.


In [29]:
a=np.arange(6).reshape(2,3)
for i in np.nditer(a,flags=['buffered'],op_dtypes=[float]):
  print(i)

0.0
1.0
2.0
3.0
4.0
5.0


21. Use nditer() to iterate over a mixed data type array, where some elements are floats
and others are integers.

In [30]:
a=np.array([1,2.3,4,5.6])
for i in np.nditer(a):
  print(i)

1.0
2.3
4.0
5.6


22. Create a 2D array and iterate over it using nditer() with op_dtypes set to different
types. Observe and explain the results.

In [31]:
a=np.arange(6).reshape(2,3)
for i in np.nditer(a,flags=['buffered'],op_dtypes=[float]):
  print(i)
#heree all the int became float

0.0
1.0
2.0
3.0
4.0
5.0


# Iterating with Different Step Sizes

23.Create a 1D array of 10 elements and iterate over it using a step size of 2. Print the
accessed elements.


In [32]:
a=np.arange(10)
for i in np.nditer(a[::2]):
  print(i)

0
2
4
6
8


24.Iterate over every second element of a 2D array along with indices of the elements

In [40]:
a=np.arange(9).reshape(3,3)
print(a)
print("---------------------------------------")
for x,i in np.ndenumerate(a[::2]):
  print(x,i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
---------------------------------------
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 6
(1, 1) 7
(1, 2) 8


25.Create a 3D array and iterate over every second element. Print the elements accessed
in each step along with indices of element.

In [39]:
a=np.arange(8).reshape(2,2,2)

print(a)
print("-----------------------")
for x in np.ndenumerate(a[::2]):
  print(x)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
-----------------------
((0, 0, 0), 0)
((0, 0, 1), 1)
((0, 1, 0), 2)
((0, 1, 1), 3)
