#Creating array

1. Create a 1D NumPy array containing the integers from 0 to 9.

In [1]:
import numpy as np

arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


2. Create a 2D NumPy array of shape (3, 3) with values ranging from 1 to 9.

In [ ]:
import numpy as np

arr=np.arange(1,10).reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


3. Create a 3x3 identity matrix using NumPy.

In [2]:
import numpy as np

arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Generate a NumPy array of 10 random numbers between 0 and 1.

In [8]:
import numpy as np

# arr=np.arange(0,1,.1)
# print(arr)
a=np.random.rand(10)
print(a)


[0.22292324 0.328635   0.3203851  0.13706614 0.3722549  0.72632735
 0.76073729 0.35767616 0.99704388 0.86670147]


5. Create an array of 10 zeros and another of 10 ones.

In [ ]:
import numpy as np

arr=np.zeros(10)
arr2=np.ones(10)
print(arr)
print(arr2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


# Array Indexing

6. Given the array a = np.array([10, 20, 30, 40, 50]), access the third element.

In [ ]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])
print(a)
print("-----------------------------------------")
print(a[2])

[10 20 30 40 50]
-----------------------------------------
30


7. Create a 4x4 matrix and access the element at the second row, third column.

In [ ]:
import numpy as np

a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(a)
print("-----------------------------------------")
print(a[1,2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
-----------------------------------------
7


8. Access the last element of the array a = np.array([5, 10, 15, 20, 25]).

In [ ]:
import numpy as np
a = np.array([5, 10, 15, 20, 25])
print(a)
print("-----------------------------------------")
print(a[-1])

[ 5 10 15 20 25]
-----------------------------------------
25


9. For the array a = np.array([1, 3, 5, 7, 9, 11]), access the elements at indices 1, 3, and 4


In [9]:
import numpy as np
a = np.array([1, 3, 5, 7, 9, 11])
print(a)
print("-----------------------------------------")
s=a[[1,3,4]]
print(s)
# l=[a[1],a[3],a[4]]
# print(l)


[ 1  3  5  7  9 11]
-----------------------------------------
[3 7 9]


10. Create a 3D array of shape (2, 2, 2) and access the element at position (1, 1, 1).

In [ ]:
import numpy as np
a=np.array([[[1,2],[3,4]],
            [[5,6],[7,8]]])
print(a)
print("-----------------------------------------")
print(a[1,1,1])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
-----------------------------------------
8


# Array Slicing

11. Given the array a = np.array([2, 4, 6, 8, 10, 12]), slice it to get the first 3 elements.

In [ ]:
import numpy as np
a=np.array([2, 4, 6, 8, 10, 12])
print(a)
print("-----------------------------------------")
print(a[:3])

[ 2  4  6  8 10 12]
-----------------------------------------
[2 4 6]


12. Create a 4x4 array and slice it to get the first two rows and last two columns.

In [10]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(a)
print("-----------------------------------------")
print(a[:2,2:])
print("-----------------------------------------")
print(a[:2,-2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
-----------------------------------------
[[3 4]
 [7 8]]
-----------------------------------------
[[3 4]
 [7 8]]


13. For the array a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), slice it to get every second element.

In [ ]:
import numpy as np
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a)
print("-----------------------------------------")
print(a[::2])

[0 1 2 3 4 5 6 7 8 9]
-----------------------------------------
[0 2 4 6 8]


14. Slice the last two elements from each row of a 3x4 array.

In [11]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print("-----------------------------------------")
print(a[:,2:])
print("-----------------------------------------")
print(a[:,-2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
-----------------------------------------
[[ 3  4]
 [ 7  8]
 [11 12]]
-----------------------------------------
[[ 3  4]
 [ 7  8]
 [11 12]]


15. Create a 5x5 matrix and slice out the inner 3x3 matrix.

In [ ]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(a)
print("-----------------------------------------")
print(a[1:4,1:4])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
-----------------------------------------
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


#Data Types

16. Create an array of integers from 0 to 5 and change its data type to float.

In [13]:
import numpy as np
a=np.arange(6)
print(a)
print("-----------------------------------------")
newarr=a.astype('f')
print(newarr)

[0 1 2 3 4 5]
-----------------------------------------
[0. 1. 2. 3. 4. 5.]


17.Create a NumPy array of shape (3, 3) with boolean values (True/False).

In [ ]:
import numpy as np
a=np.array([[1,0,1],[0,1,0],[1,0,1]])
print(a)
print("-----------------------------------------")
newarr=a.astype(bool)
print(newarr)

[[1 0 1]
 [0 1 0]
 [1 0 1]]
-----------------------------------------
[[ True False  True]
 [False  True False]
 [ True False  True]]


In [14]:
import numpy as np
a=np.array([[True,False,True],[True,False,True],[True,False,True]])
print(a)

[[ True False  True]
 [ True False  True]
 [ True False  True]]


18. Create an array of complex numbers (e.g., [1+2j, 3+4j, 5+6j]).

In [ ]:
import numpy as np
a=np.array([1+2j,3+4j,5+6j])
print(a)

[1.+2.j 3.+4.j 5.+6.j]


In [5]:
import numpy as np
a=np.array([1,2,3,4])
print(a)
print("-----------------------------------------")
b=a.astype(complex)
print(b)

[1 2 3 4]
-----------------------------------------
[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


19. Given an array of strings (e.g., ["1", "2", "3"]), convert it to an array of integers.

In [ ]:
import numpy as np
a=np.array(["1","2","3"])
print(a)
print("-----------------------------------------")
newa=a.astype('i')
print(newa)

['1' '2' '3']
-----------------------------------------
[1 2 3]


20. Create an array of float values and then convert it to an integer type.

In [ ]:
import numpy as np
a=np.array([1.1,1.2,1.3,1.4,1.5])
print(a)
print("-----------------------------------------")
newa=a.astype('i')
print(newa)

[1.1 1.2 1.3 1.4 1.5]
-----------------------------------------
[1 1 1 1 1]
