NumPy Universal Functions (ufunc)

In [1]:
import numpy as np

1. Create a ufunc that takes two arrays and returns the modulus (remainder) of
division for each element.

In [2]:
a=np.arange(5)
b=np.arange(5,10)
c=np.remainder(a,b)
print(c)

[0 1 2 3 4]


2. Define a ufunc that computes the cube of each element from two input
arrays and then sums them.

In [3]:
a=np.arange(1,5)
b=np.arange(5,9)

c=a**3
d=b**3
print(c)
print(d)
sum=np.add(c,d)
print(sum)
sum2=np.sum(sum)
print(sum2)
print("=======================================================")

ab=np.concatenate((a,b))
ab3=np.power(ab,3)
sum1=np.sum(ab3)
print(sum1)

[ 1  8 27 64]
[125 216 343 512]
[126 224 370 576]
1296
1296


3. Write a program to create a ufunc that checks if the elements of two arrays
are equal. Test it with sample arrays.

In [4]:
a=np.arange(1,5)
b=np.arange(5,9)

if np.array_equal(a,b)==True:
  print("Equal arrays ")
else:
  print("Unequal arrays")


Unequal arrays


Create Your Own ufunc

4. Create a ufunc that takes two arrays and returns the maximum of the two
values for each element.

In [5]:
def f1(a,b):
  return max(a,b)

c=np.frompyfunc(f1,2,1)
print(c([1,2,3],[4,5,6]))

[4 5 6]


5. Write a ufunc to compute the power of elements in two arrays, where each
element of one array is raised to the corresponding element of another
array.