In [2]:
import numpy as np

Numpy Joining Arrays

1. Concatenation of Arrays: Given two arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]),
concatenate them into one array.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]


2. Stacking Arrays Vertically: Stack the arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6])
vertically.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.stack((a,b),axis=1)
print(c)

[[1 4]
 [2 5]
 [3 6]]


3. Stacking Arrays Horizontally: Stack the arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6])
horizontally.

In [ ]:
 a = np.array([1, 2, 3])
 b = np.array([4, 5, 6])
 c = np.stack((a,b),axis=0)
 print(c)

[[1 2 3]
 [4 5 6]]


4. Stacking Multiple Arrays: Given three 1D arrays a, b, and c, stack them along a new axis.

In [ ]:
a=np.array([1, 2, 3])
b=np.array([4, 5, 6])
c=np.array([7, 8, 9])
x=np.stack((a,b,c))
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


5. Joining Arrays along Specific Axis: Create two 2D arrays a = np.array([[1, 2], [3, 4]]) and b =
np.array([[5, 6], [7, 8]]), and join them along axis 1.

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.concatenate((a,b),axis=1)
print(c)

[[1 2 5 6]
 [3 4 7 8]]


Numpy Splitting Arrays

6. Splitting an Array: Split an array a = np.array([1, 2, 3, 4, 5, 6]) into 3 equal parts.

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
b=np.array_split(a,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


7. Splitting a 2D Array: Split the 2D array a = np.array([[1, 2], [3, 4], [5, 6]]) into two equal parts
along axis 0.

In [6]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b=np.array_split(a,2,axis=0)
print(b)

[array([[1, 2],
       [3, 4]]), array([[5, 6]])]


8. Using array_split() for Uneven Splitting: Use array_split to split an array a = np.array([1, 2, 3, 4, 5,
6, 7]) into 3 parts, where the array lengths are not equal.

In [ ]:
 a = np.array([1, 2, 3, 4, 5, 6, 7])
 b=np.array_split(a,2)
 print(b)

[array([1, 2, 3, 4]), array([5, 6, 7])]


9. Splitting into Multiple Sub-arrays: Split a 2D array a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10,
11, 12]]) into 2 parts along axis 1.

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
b=np.array_split(a,2,axis=1)
print(b)

[array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]]), array([[ 3],
       [ 6],
       [ 9],
       [12]])]


10. Advanced Splitting: Split an array a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]) into three sub-arrays where
the first two contain 3 elements each, and the last contains the rest.

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
b = np.array_split(a,3)
print(b)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


Numpy Searching Arrays

11. Searching for Specific Values: Search for the index of value 4 in the array a = np.array([1, 2, 3, 4,
5, 6]).

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
x = np.searchsorted(a,4)
print(x)

3


12. Finding Indices of Maximum Value: Use Numpy to find the index of the maximum value in an
array a = np.array([10, 20, 30, 40, 50]).

In [ ]:
a = np.array([10, 20, 30, 40, 50])
x = np.max(a)
b = np.searchsorted(a,x)
print(b)


4


13. Multiple Value Search: Find the indices where the values are greater than 10 in a = np.array([5, 10,
15, 20, 25]).

In [ ]:
a = np.array([5, 10, 15, 20, 25])
x = np.where(a>10)
print(x)

(array([2, 3, 4]),)


14. Searching in a 2D Array: Find the index of value 7 in a 2D array a = np.array([[1, 2, 3], [4, 5, 6],
[7, 8, 9]]).

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x = np.where(a==7)
print(x)

(array([2]), array([0]))


15. Using where() for Conditional Search: Use np.where() to find the indices where the values in a =
np.array([10, 20, 30, 40, 50]) are greater than or equal to 30.

In [ ]:
a = np.array([10, 20, 30, 40, 50])
x = np.where(a>=30)
print(x)

(array([2, 3, 4]),)


Numpy Sorting Arrays

16. Sorting a 1D Array: Sort the array a = np.array([9, 2, 5, 1, 7]) in ascending order.

In [ ]:
a = np.array([9, 2, 5, 1, 7])
b = np.sort(a)
print(b)

[1 2 5 7 9]


17. Sorting a 2D Array by Columns: Sort the 2D array a = np.array([[1, 4, 3], [6, 5, 2]]) by its second
column.

In [ ]:
a = np.array([[1, 4, 3], [6, 5, 2]])
b = a[a[:,1].argsort()]
print(b)

[[1 4 3]
 [6 5 2]]


18. Sorting a 2D Array by Rows: Sort the rows of the 2D array a = np.array([[3, 2, 1], [6, 5, 4]]) in
ascending order.

In [ ]:
a = np.array([[3, 2, 1], [6, 5, 4]])
b = np.sort(a)
print(b)

[[1 2 3]
 [4 5 6]]


19. Advanced Sorting with Indices: Use np.argsort() to return the indices that would sort the array a =
np.array([30, 10, 50, 40, 20]).

In [ ]:
a = np.array([30, 10, 50, 40, 20])
b = np.argsort(a)
print(b)

[1 4 0 3 2]


20. Sorting Strings in an Array: Sort an array of strings a = np.array(["banana", "apple", "cherry"]).

In [ ]:
a = np.array(["banana", "apple", "cherry"])
b = np.sort(a)
print(b)

['apple' 'banana' 'cherry']


Numpy Filter Arrays

21. Filtering Values: Filter an array a = np.array([1, 2, 3, 4, 5, 6]) to extract only the values greater than 3.

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
b = []
for i in a:
  if i>3:
    b.append(True)
  else:
    b.append(False)
newarr=a[b]
print(newarr)

[4 5 6]


22. Filter with Multiple Conditions: Filter the array a = np.array([10, 15, 20, 25, 30]) to get values that
are both greater than 15 and less than 30.

In [14]:
a = np.array([10, 15, 20, 25, 30])
# b =np.logical_and(a<30,a>15)
b = []
for i in a:
  if i<30 and i>15:
    b.append(True)
  else:
    b.append(False)
newarr=a[b]
print(newarr)

[]


23. Filtering a 2D Array: Filter the 2D array a = np.array([[1, 2], [3, 4], [5, 6]]) to only include rows
where the first column is greater than 2.

In [ ]:
a = np.array([[1, 2], [3, 4], [5, 6]])
x=a[:,0]>2
newarr=a[x]
print(newarr)
print(x)

[[3 4]
 [5 6]]
[False  True  True]


24. Filtering Even Numbers: Create a boolean filter to select only the even numbers from an array a =
np.array([1, 2, 3, 4, 5, 6]).

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
b = []
for i in a:
  if i%2 == 0:
    b.append(True)
  else:
    b.append(False)
newarr=a[b]
print(newarr)

[2 4 6]


25. Advanced Filtering with np.where(): Use np.where() to replace all values greater than 20 in a =
np.array([10, 25, 30, 15, 50]) with 0.

In [ ]:
a = np.array([10, 25, 30, 15, 50])
b = np.where(a>20)
a[b] = 0
print(a)

[10  0  0 15  0]
